#pragma once

#include "design_pattern/spk_singleton.hpp"
#include "application/system/spk_define.hpp"
#include <map>

namespace spk
{
	class Keyboard : public spk::Singleton<Keyboard>
	{
		friend class spk::Singleton<Keyboard>;
		friend class KeyboardModule;

	public:
		enum Key
        {
            Backspace = 8,
            Tab = 9,
            Clear = 12,
            Return = 13,
            Shift = 16,
            Control = 17,
            Alt = 18,
            Pause = 19,
            Capslock = 20,
            Escape = 27,
            Convert = 28,
            Non_convert = 29,
            Accept = 30,
            Mode_change = 31,
            Space = 32,
            Prior = 33,
            Next = 34,
            End = 35,
            Home = 36,
            LeftArrow = 37,
            UpArrow = 38,
            RightArrow = 39,
            DownArrow = 40,
            Select = 41,
            Print = 42,
            Execute = 43,
            Snapshot = 44,
            Insert = 45,
            Delete = 46,
            Help = 47,
            Key0 = 48,
            Key1 = 49,
            Key2 = 50,
            Key3 = 51,
            Key4 = 52,
            Key5 = 53,
            Key6 = 54,
            Key7 = 55,
            Key8 = 56,
            Key9 = 57,
            A = 65,
            B = 66,
            C = 67,
            D = 68,
            E = 69,
            F = 70,
            G = 71,
            H = 72,
            I = 73,
            J = 74,
            K = 75,
            L = 76,
            M = 77,
            N = 78,
            O = 79,
            P = 80,
            Q = 81,
            R = 82,
            S = 83,
            T = 84,
            U = 85,
            V = 86,
            W = 87,
            X = 88,
            Y = 89,
            Z = 90,
            LeftWindows = 91,
            RightWindows = 92,
            App = 93,
            Sleep = 95,
            Numpad0 = 96,
            Numpad1 = 97,
            Numpad2 = 98,
            Numpad3 = 99,
            Numpad4 = 100,
            Numpad5 = 101,
            Numpad6 = 102,
            Numpad7 = 103,
            Numpad8 = 104,
            Numpad9 = 105,
            NumpadMultiply = 106,
            NumpadPlus = 107,
            NumpadSeparator = 108,
            NumpadMinus = 109,
            NumpadDecimal = 110,
            NumpadDivide = 111,
            F1 = 112,
            F2 = 113,
            F3 = 114,
            F4 = 115,
            F5 = 116,
            F6 = 117,
            F7 = 118,
            F8 = 119,
            F9 = 120,
            F10 = 121,
            F11 = 122,
            F12 = 123,
            F13 = 124,
            F14 = 125,
            F15 = 126,
            F16 = 127,
            F17 = 128,
            F18 = 129,
            F19 = 130,
            F20 = 131,
            F21 = 132,
            F22 = 133,
            F23 = 134,
            F24 = 135,
            NumLock = 144,
            Scroll = 145,
            LeftShift = 160,
            RightShift = 161,
            LeftControl = 162,
            RightControl = 163,
            LeftMenu = 164,
            RightMenu = 165,
            SemiColon = 186,
            Plus = 187,
            Comma = 188,
            Minus = 189,
            Period = 190,
            QuestionMark = 191,
            Tilde = 192,
            LeftBracket = 219,
            VerticalLine = 220,
            RightBracket = 221,
            Quote = 222,
            Unknow = 223,
            AngleBracket = 226,
            Process = 229,
        };
		static inline std::map<Keyboard::Key, std::wstring> KeyToStringMap = {
            {Keyboard::Key::Backspace, L"Backspace"},
            {Keyboard::Key::Tab, L"Tab"},
            {Keyboard::Key::Clear, L"Clear"},
            {Keyboard::Key::Return, L"Return"},
            {Keyboard::Key::Shift, L"Shift"},
            {Keyboard::Key::Control, L"Control"},
            {Keyboard::Key::Alt, L"Alt"},
            {Keyboard::Key::Pause, L"Pause"},
            {Keyboard::Key::Capslock, L"Capslock"},
            {Keyboard::Key::Escape, L"Escape"},
            {Keyboard::Key::Convert, L"Convert"},
            {Keyboard::Key::Non_convert, L"Non_convert"},
            {Keyboard::Key::Accept, L"Accept"},
            {Keyboard::Key::Mode_change, L"Mode_change"},
            {Keyboard::Key::Space, L"Space"},
            {Keyboard::Key::Prior, L"Prior"},
            {Keyboard::Key::Next, L"Next"},
            {Keyboard::Key::End, L"End"},
            {Keyboard::Key::Home, L"Home"},
            {Keyboard::Key::LeftArrow, L"LeftArrow"},
            {Keyboard::Key::UpArrow, L"UpArrow"},
            {Keyboard::Key::RightArrow, L"RightArrow"},
            {Keyboard::Key::DownArrow, L"DownArrow"},
            {Keyboard::Key::Select, L"Select"},
            {Keyboard::Key::Print, L"Print"},
            {Keyboard::Key::Execute, L"Execute"},
            {Keyboard::Key::Snapshot, L"Snapshot"},
            {Keyboard::Key::Insert, L"Insert"},
            {Keyboard::Key::Delete, L"Delete"},
            {Keyboard::Key::Help, L"Help"},
            {Keyboard::Key::Key0, L"Key0"},
            {Keyboard::Key::Key1, L"Key1"},
            {Keyboard::Key::Key2, L"Key2"},
            {Keyboard::Key::Key3, L"Key3"},
            {Keyboard::Key::Key4, L"Key4"},
            {Keyboard::Key::Key5, L"Key5"},
            {Keyboard::Key::Key6, L"Key6"},
            {Keyboard::Key::Key7, L"Key7"},
            {Keyboard::Key::Key8, L"Key8"},
            {Keyboard::Key::Key9, L"Key9"},
            {Keyboard::Key::A, L"A"},
            {Keyboard::Key::B, L"B"},
            {Keyboard::Key::C, L"C"},
            {Keyboard::Key::D, L"D"},
            {Keyboard::Key::E, L"E"},
            {Keyboard::Key::F, L"F"},
            {Keyboard::Key::G, L"G"},
            {Keyboard::Key::H, L"H"},
            {Keyboard::Key::I, L"I"},
            {Keyboard::Key::J, L"J"},
            {Keyboard::Key::K, L"K"},
            {Keyboard::Key::L, L"L"},
            {Keyboard::Key::M, L"M"},
            {Keyboard::Key::N, L"N"},
            {Keyboard::Key::O, L"O"},
            {Keyboard::Key::P, L"P"},
            {Keyboard::Key::Q, L"Q"},
            {Keyboard::Key::R, L"R"},
            {Keyboard::Key::S, L"S"},
            {Keyboard::Key::T, L"T"},
            {Keyboard::Key::U, L"U"},
            {Keyboard::Key::V, L"V"},
            {Keyboard::Key::W, L"W"},
            {Keyboard::Key::X, L"X"},
            {Keyboard::Key::Y, L"Y"},
            {Keyboard::Key::Z, L"Z"},
            {Keyboard::Key::LeftWindows, L"LeftWindows"},
            {Keyboard::Key::RightWindows, L"RightWindows"},
            {Keyboard::Key::App, L"App"},
            {Keyboard::Key::Sleep, L"Sleep"},
            {Keyboard::Key::Numpad0, L"Numpad0"},
            {Keyboard::Key::Numpad1, L"Numpad1"},
            {Keyboard::Key::Numpad2, L"Numpad2"},
            {Keyboard::Key::Numpad3, L"Numpad3"},
            {Keyboard::Key::Numpad4, L"Numpad4"},
            {Keyboard::Key::Numpad5, L"Numpad5"},
            {Keyboard::Key::Numpad6, L"Numpad6"},
            {Keyboard::Key::Numpad7, L"Numpad7"},
            {Keyboard::Key::Numpad8, L"Numpad8"},
            {Keyboard::Key::Numpad9, L"Numpad9"},
            {Keyboard::Key::NumpadMultiply, L"NumpadMultiply"},
            {Keyboard::Key::NumpadPlus, L"NumpadPlus"},
            {Keyboard::Key::NumpadSeparator, L"NumpadSeparator"},
            {Keyboard::Key::NumpadMinus, L"NumpadMinus"},
            {Keyboard::Key::NumpadDecimal, L"NumpadDecimal"},
            {Keyboard::Key::NumpadDivide, L"NumpadDivide"},
            {Keyboard::Key::F1, L"F1"},
            {Keyboard::Key::F2, L"F2"},
            {Keyboard::Key::F3, L"F3"},
            {Keyboard::Key::F4, L"F4"},
            {Keyboard::Key::F5, L"F5"},
            {Keyboard::Key::F6, L"F6"},
            {Keyboard::Key::F7, L"F7"},
            {Keyboard::Key::F8, L"F8"},
            {Keyboard::Key::F9, L"F9"},
            {Keyboard::Key::F10, L"F10"},
            {Keyboard::Key::F11, L"F11"},
            {Keyboard::Key::F12, L"F12"},
            {Keyboard::Key::F13, L"F13"},
            {Keyboard::Key::F14, L"F14"},
            {Keyboard::Key::F15, L"F15"},
            {Keyboard::Key::F16, L"F16"},
            {Keyboard::Key::F17, L"F17"},
            {Keyboard::Key::F18, L"F18"},
            {Keyboard::Key::F19, L"F19"},
            {Keyboard::Key::F20, L"F20"},
            {Keyboard::Key::F21, L"F21"},
            {Keyboard::Key::F22, L"F22"},
            {Keyboard::Key::F23, L"F23"},
            {Keyboard::Key::F24, L"F24"},
            {Keyboard::Key::NumLock, L"NumLock"},
            {Keyboard::Key::Scroll, L"Scroll"},
            {Keyboard::Key::LeftShift, L"LeftShift"},
            {Keyboard::Key::RightShift, L"RightShift"},
            {Keyboard::Key::LeftControl, L"LeftControl"},
            {Keyboard::Key::RightControl, L"RightControl"},
            {Keyboard::Key::LeftMenu, L"LeftMenu"},
            {Keyboard::Key::RightMenu, L"RightMenu"},
            {Keyboard::Key::SemiColon, L"SemiColon"},
            {Keyboard::Key::Plus, L"Plus"},
            {Keyboard::Key::Comma, L"Comma"},
            {Keyboard::Key::Minus, L"Minus"},
            {Keyboard::Key::Period, L"Period"},
            {Keyboard::Key::QuestionMark, L"QuestionMark"},
            {Keyboard::Key::Tilde, L"Tilde"},
            {Keyboard::Key::LeftBracket, L"LeftBracket"},
            {Keyboard::Key::VerticalLine, L"VerticalLine"},
            {Keyboard::Key::RightBracket, L"RightBracket"},
            {Keyboard::Key::Quote, L"Quote"},
            {Keyboard::Key::Unknow, L"Unknow"},
            {Keyboard::Key::AngleBracket, L"AngleBracket"},
            {Keyboard::Key::Process, L"Process"},
        };
		static inline const std::wstring UnknowKeyName = L"Unknow key";
		static const size_t NB_KEYS = 256;

		InputStatus _keys[NB_KEYS];

	private:
		Keyboard();
		
		void pressKey(const Key &p_key);
		void releaseKey(const Key &p_key);

		void update();

	public:
		const InputStatus &key(const Key &p_key) const
		{
			return (_keys[static_cast<size_t>(p_key)]);
		}

		static const std::wstring& keyToString(const Keyboard::Key& p_key);
	};

	const std::wstring& to_wstring(const Keyboard::Key& p_key);
}